plugins { id 'com.android.application' }
android {
    namespace 'pl.mindupgrade.android'
    compileSdk 35
    defaultConfig {
        applicationId 'pl.mindupgrade.android'
        minSdk 28
        targetSdk 35
        versionCode 6
        versionName '0.4.0-bibi'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies {
    implementation 'androidx.browser:browser:1.8.0'
    implementation 'androidx.webkit:webkit:1.12.1'
    implementation 'net.java.dev.jna:jna:5.18.1@aar'
    implementation 'com.alphacephei:vosk-android:0.3.75@aar'
}
